import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { format as formatWithPrettier } from "prettier";
import { parse as parseYaml } from "yaml";
import { buildProtocolModelSchema } from "../src/protocol-model-schema.mjs";

const contractsRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = path.resolve(contractsRoot, "..");
const quicktypeEntrypoint = path.join(contractsRoot, "node_modules", "quicktype", "dist", "index.js");
const eventUnionSchema = path.join(contractsRoot, "schemas", "event.schema.json");
const eventSchemas = fs.readdirSync(path.join(contractsRoot, "schemas", "events"))
  .filter((name) => name.endsWith(".schema.json"))
  .sort()
  .map((name) => path.join(contractsRoot, "schemas", "events", name));
const envelopeSchema = path.join(contractsRoot, "schemas", "event-envelope.v1.schema.json");
const checkOnly = process.argv.includes("--check");
const temporaryDirectory = fs.mkdtempSync(path.join(os.tmpdir(), "live-qs-contracts-"));
const protocolSchema = path.join(temporaryDirectory, "protocol.schema.json");

const openApi = parseYaml(fs.readFileSync(path.join(contractsRoot, "openapi.yaml"), "utf8"));
fs.writeFileSync(protocolSchema, JSON.stringify(buildProtocolModelSchema(openApi), null, 2));

const commonArguments = [
  "--src", protocolSchema,
  "--additional-schema", eventUnionSchema,
  ...eventSchemas.flatMap((schema) => ["--additional-schema", schema]),
  "--additional-schema", envelopeSchema,
  "--src-lang", "schema",
  "--top-level", "ProtocolModels",
  "--no-date-times",
  "--telemetry", "disable",
];

const targets = [
  {
    path: "server/src/generated/contract-models.ts",
    arguments: ["--lang", "typescript", "--just-types", "--prefer-unions"],
    format: formatTypeScript,
  },
  {
    path: "web/src/generated/contract-models.ts",
    arguments: ["--lang", "typescript", "--just-types", "--prefer-unions"],
    format: formatTypeScript,
  },
  {
    path: "windows/LiveQs.Windows.Core/Generated/ContractModels.g.cs",
    arguments: [
      "--lang", "csharp",
      "--namespace", "LiveQs.Windows.Core.Contracts",
      "--framework", "SystemTextJson",
      "--features", "complete",
    ],
    format: formatCSharp,
  },
  {
    path: "android/app/src/main/java/com/ailife/android/generated/ContractModels.g.kt",
    arguments: [
      "--lang", "kotlin",
      "--package", "com.ailife.android.generated",
      "--framework", "kotlinx",
      "--acronym-style", "camel",
    ],
    format: formatKotlin,
  },
];

const staleTargets = [];

try {
  for (const [index, target] of targets.entries()) {
    const temporaryOutput = path.join(temporaryDirectory, `generated-${index}${path.extname(target.path)}`);
    const result = spawnSync(
      process.execPath,
      [quicktypeEntrypoint, ...commonArguments, ...target.arguments, "--out", temporaryOutput],
      { cwd: contractsRoot, encoding: "utf8" },
    );

    if (result.status !== 0) {
      process.stderr.write(result.stderr || result.stdout || "quicktype failed without output.\n");
      process.exit(result.status ?? 1);
    }

    const unformatted = [
      "// <auto-generated />",
      "// Generated from contracts/openapi.yaml and contracts/schemas/event.schema.json.",
      "// Run `npm --prefix contracts run generate`; do not edit by hand.",
      "",
      fs.readFileSync(temporaryOutput, "utf8").replaceAll("\r\n", "\n").trimEnd(),
      "",
    ].join("\n");
    const generated = await target.format(unformatted);
    const destination = path.join(repositoryRoot, target.path);
    const current = fs.existsSync(destination)
      ? fs.readFileSync(destination, "utf8").replaceAll("\r\n", "\n")
      : null;

    if (current === generated) {
      continue;
    }
    if (checkOnly) {
      staleTargets.push(target.path);
      continue;
    }

    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.writeFileSync(destination, generated, "utf8");
    process.stdout.write(`Generated ${target.path}\n`);
  }
} finally {
  fs.rmSync(temporaryDirectory, { recursive: true, force: true });
}

if (staleTargets.length > 0) {
  process.stderr.write(
    `Generated contract models are stale:\n${staleTargets.map((target) => `- ${target}`).join("\n")}\n` +
    "Run `npm --prefix contracts run generate` and commit the results.\n",
  );
  process.exit(1);
}

if (checkOnly) {
  process.stdout.write("Generated contract models are synchronized.\n");
}

async function formatTypeScript(source) {
  return formatWithPrettier(source.replaceAll("[key: string]: any", "[key: string]: unknown"), {
    parser: "typescript",
    tabWidth: 2,
    useTabs: false,
  });
}

function formatCSharp(source) {
  source = source
    .replace("\n// <auto-generated />\n//\n// To parse", "\n// To parse")
    .replaceAll("LiveQs.Windows.Core.Contracts.Converter.Settings", "LiveQs.Windows.Core.Contracts.ContractJson.Options")
    .replace("internal static class Converter", "public static class ContractJson")
    .replace("public static readonly JsonSerializerOptions Settings", "public static readonly JsonSerializerOptions Options");
  const namespace = "LiveQs.Windows.Core.Contracts";
  const marker = `namespace ${namespace}\n{\n`;
  const markerIndex = source.indexOf(marker);
  if (markerIndex < 0) {
    throw new Error("Generated C# namespace block was not found.");
  }

  const namespaceAndTrailer = source.slice(markerIndex + marker.length).trimEnd();
  const trailerIndex = namespaceAndTrailer.indexOf("\n#pragma warning restore");
  const trailer = trailerIndex >= 0 ? namespaceAndTrailer.slice(trailerIndex) : "";
  let body = (trailerIndex >= 0 ? namespaceAndTrailer.slice(0, trailerIndex) : namespaceAndTrailer).trimEnd();
  if (!body.endsWith("}")) {
    throw new Error("Generated C# namespace block was not closed.");
  }
  body = body.slice(0, -1).trimEnd()
    .split("\n")
    .map((line) => line.startsWith("    ") ? line.slice(4) : line)
    .join("\n");

  const fileScoped = `${source.slice(0, markerIndex)}namespace ${namespace};\n\n${body}${trailer}\n`;
  return fileScoped
    .replace(
      /(\[JsonIgnore\(Condition = JsonIgnoreCondition\.WhenWritingNull\)\]\n(?:\s*\[[^\n]+\]\n)*\s*public )([A-Z][A-Za-z0-9<>]*|string)(\s+[A-Za-z][A-Za-z0-9]*\s*\{ get; set; \})/g,
      "$1$2?$3",
    )
    .replaceAll(
      "var value = reader.GetString();\n        if (value.Length",
      "var value = reader.GetString() ?? throw new JsonException(\"Expected a string.\");\n        if (value.Length",
    );
}

function formatKotlin(source) {
  return source
    .replace(
      /import kotlinx\.serialization\.\*\nimport kotlinx\.serialization\.json\.\*\nimport kotlinx\.serialization\.descriptors\.\*\nimport kotlinx\.serialization\.encoding\.\*\n/,
      "import kotlinx.serialization.SerialName\nimport kotlinx.serialization.Serializable\nimport kotlinx.serialization.json.JsonObject\nimport kotlinx.serialization.json.JsonElement\n",
    )
    .replace(/(data|enum) class ([A-Za-z0-9_]+) \(/g, "$1 class $2(")
    .replace(
      /(\s*@SerialName\("[^"]+"\) )([A-Z][A-Za-z0-9]*)(\("[^"]+"\)[,;])/g,
      (_, prefix, name, suffix) => `${prefix}${toUpperSnakeCase(name)}${suffix}`,
    );
}

function toUpperSnakeCase(value) {
  return value.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}
