import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const contractsRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = path.resolve(contractsRoot, "..");
const quicktypeEntrypoint = path.join(contractsRoot, "node_modules", "quicktype", "dist", "index.js");
const eventUnionSchema = path.join(contractsRoot, "schemas", "event.schema.json");
const eventSchemas = fs.readdirSync(path.join(contractsRoot, "schemas", "events"))
  .filter((name) => name.endsWith(".schema.json"))
  .sort()
  .map((name) => path.join(contractsRoot, "schemas", "events", name));
const envelopeSchema = path.join(contractsRoot, "schemas", "event-envelope.v1.schema.json");
const checkOnly = process.argv.includes("--check");

const commonArguments = [
  "--src", eventUnionSchema,
  ...eventSchemas.flatMap((schema) => ["--additional-schema", schema]),
  "--additional-schema", envelopeSchema,
  "--src-lang", "schema",
  "--top-level", "Event",
  "--no-date-times",
  "--telemetry", "disable",
];

const targets = [
  {
    path: "server/src/generated/contract-models.ts",
    arguments: ["--lang", "typescript", "--just-types", "--prefer-unions"],
  },
  {
    path: "web/src/generated/contract-models.ts",
    arguments: ["--lang", "typescript", "--just-types", "--prefer-unions"],
  },
  {
    path: "windows/LiveQs.Windows.Core/Generated/ContractModels.g.cs",
    arguments: [
      "--lang", "csharp",
      "--namespace", "LiveQs.Windows.Core.Contracts",
      "--features", "just-types",
    ],
  },
  {
    path: "android/app/src/main/java/com/ailife/android/generated/ContractModels.g.kt",
    arguments: [
      "--lang", "kotlin",
      "--package", "com.ailife.android.generated",
      "--framework", "just-types",
    ],
  },
];

const temporaryDirectory = fs.mkdtempSync(path.join(os.tmpdir(), "live-qs-contracts-"));
const staleTargets = [];

try {
  for (const [index, target] of targets.entries()) {
    const temporaryOutput = path.join(temporaryDirectory, `generated-${index}${path.extname(target.path)}`);
    const result = spawnSync(
      process.execPath,
      [quicktypeEntrypoint, ...commonArguments, ...target.arguments, "--out", temporaryOutput],
      { cwd: contractsRoot, encoding: "utf8" },
    );

    if (result.status !== 0) {
      process.stderr.write(result.stderr || result.stdout || "quicktype failed without output.\n");
      process.exit(result.status ?? 1);
    }

    const generated = [
      "// <auto-generated />",
      "// Generated from contracts/schemas/event.schema.json.",
      "// Run `npm --prefix contracts run generate`; do not edit by hand.",
      "",
      fs.readFileSync(temporaryOutput, "utf8").replaceAll("\r\n", "\n").trimEnd(),
      "",
    ].join("\n");
    const destination = path.join(repositoryRoot, target.path);
    const current = fs.existsSync(destination)
      ? fs.readFileSync(destination, "utf8").replaceAll("\r\n", "\n")
      : null;

    if (current === generated) {
      continue;
    }
    if (checkOnly) {
      staleTargets.push(target.path);
      continue;
    }

    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.writeFileSync(destination, generated, "utf8");
    process.stdout.write(`Generated ${target.path}\n`);
  }
} finally {
  fs.rmSync(temporaryDirectory, { recursive: true, force: true });
}

if (staleTargets.length > 0) {
  process.stderr.write(
    `Generated contract models are stale:\n${staleTargets.map((target) => `- ${target}`).join("\n")}\n` +
    "Run `npm --prefix contracts run generate` and commit the results.\n",
  );
  process.exit(1);
}

if (checkOnly) {
  process.stdout.write("Generated contract models are synchronized.\n");
}
