global using System.IO;
global using System.Net.Http;
global using MessageBox = System.Windows.MessageBox;
global using Button = System.Windows.Controls.Button;
global using UserControl = System.Windows.Controls.UserControl;
global using Color = System.Windows.Media.Color;
global using Brushes = System.Windows.Media.Brushes;
global using Pen = System.Windows.Media.Pen;
global using Point = System.Windows.Point;
global using Size = System.Windows.Size;
global using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
